### ISSUE TITLE
Does it consider to support socks5 proxy ?

### ISSUE THREAD

**Issue by Jamlee** [faceair/gotit#1]
Is it design to provide a  center proxy cache server ? when cloning library, the library whom come from `golang.org` may be blocked.  Could i add a socks feature to this repo ? 

![image](https://user-images.githubusercontent.com/5196641/46902398-70d43700-cef7-11e8-9fba-e6033af06ca3.png)

**Comment by faceair** [comment]
`http.Client` and `go get` will read proxy settings from `HTTP_PROXY` and `HTTPS_PROXY` environment variables, you can run gotit with these environment variables.

I haven't tested the socks5 proxy yet, and [it should be supported](https://github.com/golang/go/blob/da6c168378b4c1deb2a731356f1f438e4723b8a7/src/net/http/transport.go#L115). You can set `HTTPS_PROXY` to `socks5://127.0.0.1:1087`, welcome to help test.

**Comment by Jamlee** [comment]
got it

**Comment by Jamlee** [comment]
yes, i test it  and ensure it can work:
```
# start server
GIT_SSL_NO_VERIFY=true HTTP_PROXY=http://127.0.0.1:1087   HTTPS_PROXY=http://127.0.0.1:1087  gotit -port 8000  -gopath `pwd`/go

# start go get
HTTP_PROXY=http://127.0.0.1:8000 HTTPS_PROXY=http://127.0.0.1:8000 GIT_SSL_NO_VERIFY=true  go get  -v -insecure github.com/minio/minio
```
